<?php

/**
 * LRCODE
 * ============================================================================
 * 版权所有 2016-2030 江苏蓝儒网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.lanru.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * Author: 潇声
 * Date: 2019-06
 */

namespace app\common\controller;

use think\facade\Config;
use think\Controller;
use think\facade\Request;

/**
 * @brief 全站基类
 * Class Base
 * @package app\common\controller
 */
class Base extends Controller
{
    public function initialize()
    {
        parent::initialize();

        $this->assign('site', Config::get('site.'));
    }

    protected function fetch($template = '', $vars = [], $config = [])
    {
        if (Config::get('template.view_path')) {
            if (empty($template)) {
                $template = Request::module() . DS . strtolower(Request::controller()) . DS . Request::action();
            } else {
                $template = Request::module() . DS . strtolower(Request::controller()) . DS . $template;
            }
        }

        return parent::fetch($template, $vars, $config); // TODO: Change the autogenerated stub
    }
}