<?php

/**
 * LRCODE
 * ============================================================================
 * 版权所有 2016-2030 江苏蓝儒网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.lanru.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * Author: 潇声
 * Date: 2019-08
 */

namespace app\api\controller;


use app\common\controller\Api;
use lanru\Date;
use think\Db;
use think\Exception;
use think\facade\Config;

class Signin extends Api
{
    protected $noNeedLogin = '';
    protected $noNeedRight = '*';
    protected $user = [];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = $this->auth->getUser();
    }

    public function check()
    {
        $config = Config::get("site.");
        $signdata = $config['signinscore'];
        $lastdata = \app\common\model\Signin::where('user_id', $this->auth->id)->order('createtime', 'desc')->find();
        $successions = $lastdata && $lastdata['createtime'] > Date::unixtime('day', -1) ? $lastdata['successions'] : 0;
        $score = isset($signdata['s' . $successions]) ? $signdata['s' . $successions] : $signdata['sn'];
        $signin = \app\common\model\Signin::where('user_id', $this->user['id'])->whereTime('createtime', 'today')->find();

        return $this->success($score, $signin ? 1 : 0);
    }

    public function index()
    {
        $config = Config::get("site.");
        $signdata = $config['signinscore'];

        $lastdata = \app\common\model\Signin::where("user_id", $this->auth->id)->order('createtime', 'desc')->find();
        $successions = $lastdata && $lastdata['createtime'] > Date::unixtime('day', -1) ? $lastdata['successions'] : 0;
        $signin = \app\common\model\Signin::where('user_id', $this->auth->id)->whereTime('createtime', 'today')->find();
        
        if ($signin) {
            return $this->error('今天已签到,请明天再来!');
        } else {
            $successions++;
            $score = isset($signdata['s' . $successions]) ? $signdata['s' . $successions] : $signdata['sn'];
            Db::startTrans();
            try {
                \app\common\model\Signin::create(['user_id' => $this->auth->id, 'successions' => $successions, 'createtime' => time()]);
                \app\common\model\User::score($score, $this->auth->id, "连续签到{$successions}天");
                Db::commit();
            } catch (Exception $e) {
                Db::rollback();
                return $this->error('签到失败,请稍后重试');
            }
            return $this->success('签到成功!连续签到' . $successions . '天!获得' . $score . '学豆');
        }
    }
}